-- ------------------------------------------------------------------------------
--   ScenarioWriterCafe スキーマ（テーブル定義のみ・データ無し）
--   scwSchema.sql   初期設定 swSetup.php のインストールで実行される。
--   utf8mb4 / utf8mb4_general_ci。CREATE TABLE IF NOT EXISTS（既存は保持）。
--   2026-09 管理者機能の廃止に伴い SW_ADMIN 表は作らない（既存 DB に残っていても害はない）。
-- ------------------------------------------------------------------------------
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE IF NOT EXISTS `SW_CHARACTER` (
  `CHARACTER_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'CHARACTER_ID',
  `SCENARIO_ID` int(11) DEFAULT NULL COMMENT 'SCENARIO_ID',
  `CHARACTER_ORDER_NO` double DEFAULT NULL COMMENT '並び順',
  `CHARACTER_NAME` varchar(256) DEFAULT NULL COMMENT '登場人物名',
  `CHARACTER_CHARA` longtext COMMENT '登場人物説明',
  `COPY_SOURCE_ID` int(11) DEFAULT NULL COMMENT '複写元',
  PRIMARY KEY (`CHARACTER_ID`),
  KEY `SW_CHARACTER_KEY_SCENARIO_ID` (`SCENARIO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=561 DEFAULT CHARSET=utf8mb4 COMMENT='登場人物設定';
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE IF NOT EXISTS `SW_CONTACT` (
  `CONTACT_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `CONTACT_MAILAD` varchar(256) DEFAULT NULL COMMENT 'MAILAD',
  `CONTACT_NAME` varchar(256) DEFAULT NULL COMMENT 'NAME',
  `CONTACT_SUBJECT` varchar(256) DEFAULT NULL COMMENT 'SUBJECT',
  `CONTACT_BODY` longtext COMMENT 'BODY',
  `CONTACT_REPLY` longtext COMMENT 'REPLY',
  `CONTACT_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'DATE',
  PRIMARY KEY (`CONTACT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE IF NOT EXISTS `SW_SCENARIO` (
  `SCENARIO_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'シナリオID',
  `USER_ID` int(11) DEFAULT NULL COMMENT 'USER_ID',
  `SCENARIO_TITLE` varchar(256) DEFAULT NULL COMMENT 'タイトル',
  `SCENARIO_SUBTITLE` varchar(256) DEFAULT NULL COMMENT 'サブタイトル',
  `SCENARIO_WRITER_NAME` varchar(256) DEFAULT NULL COMMENT '作者名',
  `SCENARIO_MEMO` longtext COMMENT 'メモ',
  `SCENARIO_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '執筆日',
  `SCENARIO_CATEGORY` int(11) DEFAULT NULL COMMENT '分類',
  PRIMARY KEY (`SCENARIO_ID`),
  KEY `SW_SCENARIO_KEY_USER_ID` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=67 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE IF NOT EXISTS `SW_SCENARIO_LINES` (
  `SCENARIO_LINES_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'SCENARIO_LINES_ID',
  `SCENARIO_ID` int(11) DEFAULT NULL COMMENT 'SCENARIO_ID',
  `SCENE_ID` int(11) DEFAULT NULL COMMENT 'SCENE_ID',
  `SCENARIO_LINES_ORDER_NO` double DEFAULT NULL COMMENT '並び順',
  `SCENARIO_TYPE` int(11) DEFAULT NULL COMMENT 'シナリオ種別',
  `CHARACTER_ID` int(11) DEFAULT NULL COMMENT '登場人物',
  `SCENARIO_LINES` longtext COMMENT '台詞',
  PRIMARY KEY (`SCENARIO_LINES_ID`),
  KEY `SW_SCENARIO_LINES_KEY_SCENARIO_ID` (`SCENARIO_ID`),
  KEY `SW_SCENARIO_LINES_KEY_SCENE_ID` (`SCENE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=32645 DEFAULT CHARSET=utf8mb4 COMMENT='シナリオ';
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE IF NOT EXISTS `SW_SCENE` (
  `SCENE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'SCENE_ID',
  `SCENARIO_ID` int(11) DEFAULT NULL COMMENT 'SCENARIO_ID',
  `SCENE_ORDER_NO` double DEFAULT NULL COMMENT '場面順番',
  `SCENE_VALID_CD` int(11) DEFAULT NULL COMMENT '有効',
  `SCENE_NAME` varchar(256) DEFAULT NULL COMMENT '場面名称',
  `SCENE_DESCRIPTION` longtext COMMENT '場面説明',
  `SCENE_TIME_MIN` int(11) DEFAULT NULL COMMENT '時間（分）',
  `SCENE_TIME_SEC` int(11) DEFAULT NULL COMMENT '時間（秒）',
  `COPY_SOURCE_ID` int(11) DEFAULT NULL COMMENT '複写元',
  PRIMARY KEY (`SCENE_ID`),
  KEY `SW_SCENE_KEY_SCENARIO_ID` (`SCENARIO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=191 DEFAULT CHARSET=utf8mb4 COMMENT='場面設定';
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE IF NOT EXISTS `SW_SYNOPSIS` (
  `SYNOPSIS_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'SYNOPSIS_ID',
  `SCENARIO_ID` int(11) DEFAULT NULL COMMENT 'SCENARIO_ID',
  `SYNOPSIS` longtext COMMENT 'SYNOPSIS',
  `UPDATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  PRIMARY KEY (`SYNOPSIS_ID`),
  KEY `SW_SYNOPSIS_KEY_SCENARIO_ID` (`SCENARIO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='シノプシス';
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE IF NOT EXISTS `SW_USER` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ユーザーID',
  `USER_MAILAD` varchar(256) DEFAULT NULL COMMENT 'メールアドレス',
  `USER_PASSWD` varchar(256) DEFAULT NULL COMMENT 'パスワード',
  `USER_NAME` varchar(256) DEFAULT NULL COMMENT 'ユーザー名',
  `USER_MAX_SCENARIO` int(11) DEFAULT NULL COMMENT '作成可能シナリオ数',
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `SW_USER_KEY_USER_ID` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COMMENT='USER_INFO';
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE IF NOT EXISTS `SW_USER_LOGIN_INFO` (
  `USER_LOGIN_ID` varchar(32) NOT NULL COMMENT 'USERログインID',
  `USER_ID` varchar(256) DEFAULT NULL COMMENT 'USER_ID',
  `USER_LOGIN_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'USERログイン日時',
  PRIMARY KEY (`USER_LOGIN_ID`),
  UNIQUE KEY `SW_USER_LOGIN_INFO_KEY_USER_LOGIN_ID` (`USER_LOGIN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='USERログイン情報';
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE IF NOT EXISTS `SW_USER_OPTION` (
  `USER_OPTION_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'USER_OPTION_ID',
  `USER_ID` int(11) DEFAULT NULL COMMENT 'USER_ID',
  `USER_OPTION_STYLE_ID` int(11) DEFAULT NULL COMMENT 'スタイルID',
  `USER_OPTION_STYLE_ORDER_NO` int(11) DEFAULT NULL COMMENT '並び順',
  `USER_OPTION_STYLE_NAME` varchar(256) DEFAULT NULL COMMENT 'スタイル名',
  `USER_OPTION_STYLE_FONT_SIZE` int(11) DEFAULT NULL COMMENT 'フォントサイズ',
  `USER_OPTION_STYLE_COLOR` varchar(24) DEFAULT NULL COMMENT '文字色',
  `USER_OPTION_STYLE_INDENT` int(11) DEFAULT NULL COMMENT '字下げ数',
  `USER_OPTION_STYLE_STR` varchar(24) DEFAULT NULL COMMENT '省略文字',
  `USER_OPTION_STYLE_WORD` int(11) DEFAULT NULL COMMENT '台詞',
  PRIMARY KEY (`USER_OPTION_ID`),
  UNIQUE KEY `SW_USER_OPTION_KEY_USER_OPTION_ID` (`USER_OPTION_ID`),
  KEY `SW_USER_OPTION_KEY_USER_ID` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8mb4 COMMENT='個別設定';
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE IF NOT EXISTS `SW_USER_OPTION_SETTING` (
  `USER_ID` int(11) NOT NULL COMMENT 'USER_ID',
  `CHARACTER_LENGTH` int(11) DEFAULT NULL COMMENT 'キャラクタ部の文字数',
  `BODY_LENGTH` int(11) DEFAULT NULL COMMENT 'シナリオ本文の文字数',
  `USE_KAGIKAKKO` tinyint(1) NOT NULL DEFAULT '1' COMMENT '台詞を「」で囲む(1=囲む,0=囲まない)',
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `SW_USER_OPTION_SETTING_KEY_USER_ID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ユーザーオプション設定';
/*!40101 SET character_set_client = @saved_cs_client */;
CREATE TABLE IF NOT EXISTS `SW_PREVIEW` (
  `SCENARIO_ID` int(11) NOT NULL COMMENT 'シナリオID',
  `PREVIEW_KEY` varchar(64) NOT NULL COMMENT '公開URLの鍵',
  `PREVIEW_VALID` int(11) NOT NULL DEFAULT 0 COMMENT '1=公開中',
  `UPDATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  PRIMARY KEY (`SCENARIO_ID`),
  KEY `SW_PREVIEW_KEY_PREVIEW_KEY` (`PREVIEW_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='劇団員プレビュー';

-- ------------------------------------------------------------------------------
-- 共同執筆（コラボレーション版で追加）
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `SW_SCENARIO_MEMBER` (
  `SCENARIO_ID` int(11) NOT NULL COMMENT 'シナリオID',
  `USER_ID` int(11) NOT NULL COMMENT 'ユーザーID',
  `MEMBER_ROLE` varchar(16) NOT NULL DEFAULT 'editor' COMMENT '権限 editor=編集できる reader=閲覧のみ',
  `MEMBER_TITLE` varchar(64) DEFAULT NULL COMMENT '役割名(表示用)',
  `ADD_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '追加日時',
  PRIMARY KEY (`SCENARIO_ID`,`USER_ID`),
  KEY `SW_SCENARIO_MEMBER_KEY_USER_ID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='共同執筆メンバー';

CREATE TABLE IF NOT EXISTS `SW_SCENARIO_INVITE` (
  `INVITE_KEY` varchar(64) NOT NULL COMMENT '招待URLの鍵',
  `SCENARIO_ID` int(11) NOT NULL COMMENT 'シナリオID',
  `INVITE_ROLE` varchar(16) NOT NULL DEFAULT 'editor' COMMENT '参加後の権限',
  `INVITE_TITLE` varchar(64) DEFAULT NULL COMMENT '参加後の役割名',
  `INVITE_EXPIRE` datetime DEFAULT NULL COMMENT '有効期限(NULL=無期限)',
  `INVITE_VALID` int(11) NOT NULL DEFAULT 1 COMMENT '1=有効',
  `CREATE_USER_ID` int(11) DEFAULT NULL COMMENT '発行者',
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '発行日時',
  PRIMARY KEY (`INVITE_KEY`),
  KEY `SW_SCENARIO_INVITE_KEY_SCENARIO_ID` (`SCENARIO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='共同執筆の招待';

CREATE TABLE IF NOT EXISTS `SW_ACTIVITY` (
  `ACTIVITY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SCENARIO_ID` int(11) NOT NULL COMMENT 'シナリオID',
  `USER_ID` int(11) NOT NULL COMMENT '操作したユーザー',
  `ACTIVITY_KIND` varchar(64) NOT NULL COMMENT '操作の種類',
  `ACTIVITY_NOTE` varchar(256) DEFAULT NULL COMMENT '補足(場面名など)',
  `ACTIVITY_DATE` datetime NOT NULL COMMENT '日時',
  PRIMARY KEY (`ACTIVITY_ID`),
  KEY `SW_ACTIVITY_KEY_SCENARIO_ID` (`SCENARIO_ID`,`ACTIVITY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='更新履歴';

CREATE TABLE IF NOT EXISTS `SW_PRESENCE` (
  `SCENARIO_ID` int(11) NOT NULL COMMENT 'シナリオID',
  `USER_ID` int(11) NOT NULL COMMENT 'ユーザーID',
  `PRESENCE_PAGE` varchar(64) DEFAULT NULL COMMENT '開いている画面',
  `PRESENCE_DATE` datetime NOT NULL COMMENT '最終応答日時',
  PRIMARY KEY (`SCENARIO_ID`,`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='在席';

CREATE TABLE IF NOT EXISTS `SW_SCENARIO_ROLE` (
  `ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SCENARIO_ID` int(11) NOT NULL COMMENT 'シナリオID',
  `ROLE_NAME` varchar(64) NOT NULL COMMENT '役割名',
  `ROLE_LEVEL` varchar(16) NOT NULL DEFAULT 'editor' COMMENT '権限 editor=編集できる reader=閲覧のみ',
  `ROLE_ORDER` int(11) NOT NULL DEFAULT 0 COMMENT '並び順',
  PRIMARY KEY (`ROLE_ID`),
  KEY `SW_SCENARIO_ROLE_KEY_SCENARIO_ID` (`SCENARIO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='役割の定義';
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;


-- ------------------------------------------------------------------------------
-- 既定のオプション設定スタイル（テンプレート USER_ID=0）。新規ユーザーはこれを複写する。
-- ------------------------------------------------------------------------------
DELETE FROM SW_USER_OPTION WHERE USER_ID=0;
INSERT INTO `SW_USER_OPTION` VALUES (101,0,1,100,'セリフ',12,'#000000',0,'',1),(102,0,2,200,'ト書',12,'#006400',3,'',0),(103,0,3,300,'歌詞',12,'#ff4500',4,'Song',0),(104,0,4,400,'ナレーション',12,'#000000',0,'NA',1),(105,0,5,500,'モノローグ',12,'#000000',0,'M',1),(106,0,6,600,'テロップ',12,'#ff4500',4,'T',0),(107,0,7,700,'演技指示',12,'#8b0000',4,'',0),(108,0,8,800,'音響指示',12,'#8b0000',4,'SE',0),(109,0,9,900,'照明指示',12,'#8b0000',4,'L',0),(110,0,10,1000,'フェードイン',12,'#000000',4,'(F.I)',0),(111,0,11,1100,'フェードアウト',12,'#000000',4,'(F.O)',0),(112,0,12,1200,'カットイン',12,'#000000',4,'(C.I)',0),(113,0,13,1300,'カットアウト',12,'#000000',4,'(C.O)',0),(114,0,14,1400,'カット・トゥー',12,'#000000',4,'(C.T)',0),(115,0,15,1500,'オーバーラップ',12,'#000000',4,'(O.L)',0),(116,0,16,1600,'ズームイン',12,'#000000',4,'(Z.I)',0),(117,0,17,1700,'ズームアウト',12,'#000000',4,'(Z.O)',0),(118,0,18,1800,'カメラ：パン・トゥー',12,'#000000',4,'(P.T)',0),(119,0,19,1900,'カメラ：フレームイン',12,'#000000',4,'(Fr.I)',0),(120,0,20,2000,'カメラ：フレームアウト',12,'#000000',4,'(Fr.O)',0),(121,0,21,2100,'カメラワーク',12,'#000000',4,'(C)',0);
