-- ------------------------------------------------------------------------------
--   ScenarioWriterCafe スキーマ SQLite 版（テーブル定義のみ・データ無し）
--   scwSchema.sqlite.sql   初期設定 swSetup.php のインストール（dbType=sqlite）で実行される。
--   scwSchema.sql（MySQL 版）と同じ表・列。違いは次の通り。
--     ・AUTO_INCREMENT → INTEGER PRIMARY KEY AUTOINCREMENT
--     ・timestamp ... ON UPDATE CURRENT_TIMESTAMP → DEFAULT (datetime('now','localtime')) + AFTER UPDATE トリガー
--       （SQLite の CURRENT_TIMESTAMP は UTC なので localtime を使う）
--     ・varchar は COLLATE NOCASE（MySQL の utf8mb4_general_ci と同じく大文字小文字を区別しない）
--     ・トリガーは 1 行で書く（ajaxSetup.php が行末の ; で文を分割するため）
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS SW_CHARACTER (
  CHARACTER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SCENARIO_ID INTEGER DEFAULT NULL,
  CHARACTER_ORDER_NO REAL DEFAULT NULL,
  CHARACTER_NAME VARCHAR(256) COLLATE NOCASE DEFAULT NULL,
  CHARACTER_CHARA TEXT,
  COPY_SOURCE_ID INTEGER DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS SW_CHARACTER_KEY_SCENARIO_ID ON SW_CHARACTER (SCENARIO_ID);

CREATE TABLE IF NOT EXISTS SW_CONTACT (
  CONTACT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CONTACT_MAILAD VARCHAR(256) COLLATE NOCASE DEFAULT NULL,
  CONTACT_NAME VARCHAR(256) COLLATE NOCASE DEFAULT NULL,
  CONTACT_SUBJECT VARCHAR(256) COLLATE NOCASE DEFAULT NULL,
  CONTACT_BODY TEXT,
  CONTACT_REPLY TEXT,
  CONTACT_DATE TEXT NOT NULL DEFAULT (datetime('now','localtime'))
);
CREATE TRIGGER IF NOT EXISTS SW_CONTACT_TRG_DATE AFTER UPDATE ON SW_CONTACT FOR EACH ROW WHEN NEW.CONTACT_DATE IS OLD.CONTACT_DATE BEGIN UPDATE SW_CONTACT SET CONTACT_DATE = datetime('now','localtime') WHERE CONTACT_ID = NEW.CONTACT_ID; END;

CREATE TABLE IF NOT EXISTS SW_SCENARIO (
  SCENARIO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USER_ID INTEGER DEFAULT NULL,
  SCENARIO_TITLE VARCHAR(256) COLLATE NOCASE DEFAULT NULL,
  SCENARIO_SUBTITLE VARCHAR(256) COLLATE NOCASE DEFAULT NULL,
  SCENARIO_WRITER_NAME VARCHAR(256) COLLATE NOCASE DEFAULT NULL,
  SCENARIO_MEMO TEXT,
  SCENARIO_DATE TEXT NOT NULL DEFAULT (datetime('now','localtime')),
  SCENARIO_CATEGORY INTEGER DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS SW_SCENARIO_KEY_USER_ID ON SW_SCENARIO (USER_ID);
CREATE TRIGGER IF NOT EXISTS SW_SCENARIO_TRG_DATE AFTER UPDATE ON SW_SCENARIO FOR EACH ROW WHEN NEW.SCENARIO_DATE IS OLD.SCENARIO_DATE BEGIN UPDATE SW_SCENARIO SET SCENARIO_DATE = datetime('now','localtime') WHERE SCENARIO_ID = NEW.SCENARIO_ID; END;

CREATE TABLE IF NOT EXISTS SW_SCENARIO_LINES (
  SCENARIO_LINES_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SCENARIO_ID INTEGER DEFAULT NULL,
  SCENE_ID INTEGER DEFAULT NULL,
  SCENARIO_LINES_ORDER_NO REAL DEFAULT NULL,
  SCENARIO_TYPE INTEGER DEFAULT NULL,
  CHARACTER_ID INTEGER DEFAULT NULL,
  SCENARIO_LINES TEXT
);
CREATE INDEX IF NOT EXISTS SW_SCENARIO_LINES_KEY_SCENARIO_ID ON SW_SCENARIO_LINES (SCENARIO_ID);
CREATE INDEX IF NOT EXISTS SW_SCENARIO_LINES_KEY_SCENE_ID ON SW_SCENARIO_LINES (SCENE_ID);

CREATE TABLE IF NOT EXISTS SW_SCENE (
  SCENE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SCENARIO_ID INTEGER DEFAULT NULL,
  SCENE_ORDER_NO REAL DEFAULT NULL,
  SCENE_VALID_CD INTEGER DEFAULT NULL,
  SCENE_NAME VARCHAR(256) COLLATE NOCASE DEFAULT NULL,
  SCENE_DESCRIPTION TEXT,
  SCENE_TIME_MIN INTEGER DEFAULT NULL,
  SCENE_TIME_SEC INTEGER DEFAULT NULL,
  COPY_SOURCE_ID INTEGER DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS SW_SCENE_KEY_SCENARIO_ID ON SW_SCENE (SCENARIO_ID);

CREATE TABLE IF NOT EXISTS SW_SYNOPSIS (
  SYNOPSIS_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SCENARIO_ID INTEGER DEFAULT NULL,
  SYNOPSIS TEXT,
  UPDATE_DATE TEXT NOT NULL DEFAULT (datetime('now','localtime'))
);
CREATE INDEX IF NOT EXISTS SW_SYNOPSIS_KEY_SCENARIO_ID ON SW_SYNOPSIS (SCENARIO_ID);
CREATE TRIGGER IF NOT EXISTS SW_SYNOPSIS_TRG_DATE AFTER UPDATE ON SW_SYNOPSIS FOR EACH ROW WHEN NEW.UPDATE_DATE IS OLD.UPDATE_DATE BEGIN UPDATE SW_SYNOPSIS SET UPDATE_DATE = datetime('now','localtime') WHERE SYNOPSIS_ID = NEW.SYNOPSIS_ID; END;

CREATE TABLE IF NOT EXISTS SW_USER (
  USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USER_MAILAD VARCHAR(256) COLLATE NOCASE DEFAULT NULL,
  USER_PASSWD VARCHAR(256) DEFAULT NULL,
  USER_NAME VARCHAR(256) COLLATE NOCASE DEFAULT NULL,
  USER_MAX_SCENARIO INTEGER DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS SW_USER_LOGIN_INFO (
  USER_LOGIN_ID VARCHAR(32) NOT NULL PRIMARY KEY,
  USER_ID VARCHAR(256) DEFAULT NULL,
  USER_LOGIN_DATE TEXT NOT NULL DEFAULT (datetime('now','localtime'))
);
CREATE TRIGGER IF NOT EXISTS SW_USER_LOGIN_INFO_TRG_DATE AFTER UPDATE ON SW_USER_LOGIN_INFO FOR EACH ROW WHEN NEW.USER_LOGIN_DATE IS OLD.USER_LOGIN_DATE BEGIN UPDATE SW_USER_LOGIN_INFO SET USER_LOGIN_DATE = datetime('now','localtime') WHERE USER_LOGIN_ID = NEW.USER_LOGIN_ID; END;

CREATE TABLE IF NOT EXISTS SW_USER_OPTION (
  USER_OPTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USER_ID INTEGER DEFAULT NULL,
  USER_OPTION_STYLE_ID INTEGER DEFAULT NULL,
  USER_OPTION_STYLE_ORDER_NO INTEGER DEFAULT NULL,
  USER_OPTION_STYLE_NAME VARCHAR(256) COLLATE NOCASE DEFAULT NULL,
  USER_OPTION_STYLE_FONT_SIZE INTEGER DEFAULT NULL,
  USER_OPTION_STYLE_COLOR VARCHAR(24) COLLATE NOCASE DEFAULT NULL,
  USER_OPTION_STYLE_INDENT INTEGER DEFAULT NULL,
  USER_OPTION_STYLE_STR VARCHAR(24) COLLATE NOCASE DEFAULT NULL,
  USER_OPTION_STYLE_WORD INTEGER DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS SW_USER_OPTION_KEY_USER_ID ON SW_USER_OPTION (USER_ID);

CREATE TABLE IF NOT EXISTS SW_USER_OPTION_SETTING (
  USER_ID INTEGER NOT NULL PRIMARY KEY,
  CHARACTER_LENGTH INTEGER DEFAULT NULL,
  BODY_LENGTH INTEGER DEFAULT NULL,
  USE_KAGIKAKKO INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS SW_PREVIEW (
  SCENARIO_ID INTEGER NOT NULL PRIMARY KEY,
  PREVIEW_KEY VARCHAR(64) NOT NULL,
  PREVIEW_VALID INTEGER NOT NULL DEFAULT 0,
  UPDATE_DATE TEXT NOT NULL DEFAULT (datetime('now','localtime'))
);
CREATE INDEX IF NOT EXISTS SW_PREVIEW_KEY_PREVIEW_KEY ON SW_PREVIEW (PREVIEW_KEY);

-- ------------------------------------------------------------------------------
-- 共同執筆（コラボレーション版で追加）
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS SW_SCENARIO_MEMBER (
  SCENARIO_ID INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL,
  MEMBER_ROLE VARCHAR(16) NOT NULL DEFAULT 'editor',
  MEMBER_TITLE VARCHAR(64) DEFAULT NULL,
  ADD_DATE TEXT NOT NULL DEFAULT (datetime('now','localtime')),
  PRIMARY KEY (SCENARIO_ID, USER_ID)
);
CREATE INDEX IF NOT EXISTS SW_SCENARIO_MEMBER_KEY_USER_ID ON SW_SCENARIO_MEMBER (USER_ID);

CREATE TABLE IF NOT EXISTS SW_SCENARIO_INVITE (
  INVITE_KEY VARCHAR(64) NOT NULL PRIMARY KEY,
  SCENARIO_ID INTEGER NOT NULL,
  INVITE_ROLE VARCHAR(16) NOT NULL DEFAULT 'editor',
  INVITE_TITLE VARCHAR(64) DEFAULT NULL,
  INVITE_EXPIRE TEXT DEFAULT NULL,
  INVITE_VALID INTEGER NOT NULL DEFAULT 1,
  CREATE_USER_ID INTEGER DEFAULT NULL,
  CREATE_DATE TEXT NOT NULL DEFAULT (datetime('now','localtime'))
);
CREATE INDEX IF NOT EXISTS SW_SCENARIO_INVITE_KEY_SCENARIO_ID ON SW_SCENARIO_INVITE (SCENARIO_ID);

CREATE TABLE IF NOT EXISTS SW_ACTIVITY (
  ACTIVITY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SCENARIO_ID INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL,
  ACTIVITY_KIND VARCHAR(64) NOT NULL,
  ACTIVITY_NOTE VARCHAR(256) DEFAULT NULL,
  ACTIVITY_DATE TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS SW_ACTIVITY_KEY_SCENARIO_ID ON SW_ACTIVITY (SCENARIO_ID, ACTIVITY_ID);

CREATE TABLE IF NOT EXISTS SW_PRESENCE (
  SCENARIO_ID INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL,
  PRESENCE_PAGE VARCHAR(64) DEFAULT NULL,
  PRESENCE_DATE TEXT NOT NULL,
  PRIMARY KEY (SCENARIO_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS SW_SCENARIO_ROLE (
  ROLE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SCENARIO_ID INTEGER NOT NULL,
  ROLE_NAME VARCHAR(64) NOT NULL,
  ROLE_LEVEL VARCHAR(16) NOT NULL DEFAULT 'editor',
  ROLE_ORDER INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS SW_SCENARIO_ROLE_KEY_SCENARIO_ID ON SW_SCENARIO_ROLE (SCENARIO_ID);

-- ------------------------------------------------------------------------------
-- 既定のオプション設定スタイル（テンプレート USER_ID=0）。新規ユーザーはこれを複写する。
-- ------------------------------------------------------------------------------
DELETE FROM SW_USER_OPTION WHERE USER_ID=0;
INSERT INTO SW_USER_OPTION VALUES (101,0,1,100,'セリフ',12,'#000000',0,'',1),(102,0,2,200,'ト書',12,'#006400',3,'',0),(103,0,3,300,'歌詞',12,'#ff4500',4,'Song',0),(104,0,4,400,'ナレーション',12,'#000000',0,'NA',1),(105,0,5,500,'モノローグ',12,'#000000',0,'M',1),(106,0,6,600,'テロップ',12,'#ff4500',4,'T',0),(107,0,7,700,'演技指示',12,'#8b0000',4,'',0),(108,0,8,800,'音響指示',12,'#8b0000',4,'SE',0),(109,0,9,900,'照明指示',12,'#8b0000',4,'L',0),(110,0,10,1000,'フェードイン',12,'#000000',4,'(F.I)',0),(111,0,11,1100,'フェードアウト',12,'#000000',4,'(F.O)',0),(112,0,12,1200,'カットイン',12,'#000000',4,'(C.I)',0),(113,0,13,1300,'カットアウト',12,'#000000',4,'(C.O)',0),(114,0,14,1400,'カット・トゥー',12,'#000000',4,'(C.T)',0),(115,0,15,1500,'オーバーラップ',12,'#000000',4,'(O.L)',0),(116,0,16,1600,'ズームイン',12,'#000000',4,'(Z.I)',0),(117,0,17,1700,'ズームアウト',12,'#000000',4,'(Z.O)',0),(118,0,18,1800,'カメラ：パン・トゥー',12,'#000000',4,'(P.T)',0),(119,0,19,1900,'カメラ：フレームイン',12,'#000000',4,'(Fr.I)',0),(120,0,20,2000,'カメラ：フレームアウト',12,'#000000',4,'(Fr.O)',0),(121,0,21,2100,'カメラワーク',12,'#000000',4,'(C)',0);
